AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template for S3 bucket with code of resources needed for ml apps

Parameters:
  CodePackageDate:
    Description: The date of the code package in ms.
    Type: String

Resources:
  MLCodeBaseS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ml-code-bucket
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  MLCodeBaseS3BucketName:
    Description: Name of code base bucket
    Value: !Ref MLCodeBaseS3Bucket
    Export:
      Name: !Sub ml-code-bucket-name

  MLCodeBaseS3BucketArn:
    Description: ARN of code base bucket
    Value: !GetAtt MLCodeBaseS3Bucket.Arn
    Export:
      Name: !Sub ml-code-bucket-name-arn
